[package]
name = "factom"
version = "1.0.2"
authors = ["MitchellBerry <mitchellberry+public@protonmail.com>"]
edition = "2018"
repository = "https://github.com/MitchellBerry/Factom-Client"
homepage = "https://github.com/MitchellBerry/Factom-Client"
license = "Apache-2.0"
readme = "readme.md"
maintenance = { status = "passively-maintained" }
description = "Factom API client"

[dependencies]
rand = "0.6.5"
tokio = "0.1.17"
http = "0.1.15"
hyper = "0.12.23"
hyper-tls = "0.3.1"
serde_json = "1.0.39"
serde_derive = "1.0.89"
serde =  { version = "1.0.89", features = ["derive"] }
futures = "0.1.25"